# Generated by Django 4.1.7 on 2023-02-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=100)),
                ('book_pages', models.PositiveIntegerField()),
                ('summary', models.TextField(blank=True, help_text='Summary about the book', max_length=500, null=True)),
            ],
        ),
    ]
