# Generated by Django 4.1.7 on 2023-02-23 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_pages',
        ),
    ]
