# Generated by Django 4.1.7 on 2023-02-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_system', '0002_remove_book_book_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
