# Generated by Django 4.1.7 on 2023-02-26 19:17

from django.db import migrations, models
import library_management_system.models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_system', '0005_alter_bookissue_issued_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='to_be_return_date',
            field=models.DateField(default=library_management_system.models.default_return_date),
        ),
    ]
