# Generated by Django 4.1.7 on 2023-02-27 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_system', '0006_bookissue_to_be_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='summary',
        ),
    ]
