# Generated by Django 4.1.7 on 2023-02-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_system', '0007_remove_book_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='avilable',
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=10),
        ),
    ]
