# Generated by Django 4.1.7 on 2023-03-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_system', '0010_alter_book_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('book_title', 'book_author')},
        ),
    ]
