# Generated by Django 4.1.7 on 2023-03-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_system', '0013_rename_status_booktrasaction_is_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktrasaction',
            name='is_issued',
            field=models.IntegerField(default=0),
        ),
    ]
