# Generated by Django 4.1.7 on 2023-03-20 08:55

from django.db import migrations, models
import library_management_system.models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_system', '0014_alter_booktrasaction_is_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='issued_date',
            field=models.DateField(default=library_management_system.models.issue_data),
        ),
    ]
