# Generated by Django 4.1.7 on 2023-03-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_system', '0018_booktrasaction_fine'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='booktrasaction',
            name='issued_date',
            field=models.DateField(null=True),
        ),
    ]
