# Generated by Django 4.1.7 on 2023-03-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_system', '0021_remove_booktrasaction_fine_delete_fine'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
