# Generated by Django 4.1.7 on 2023-03-29 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_system', '0022_feedbackuser_delete_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktrasaction',
            name='is_issued',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
