# Generated by Django 4.1.7 on 2023-03-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_system', '0023_alter_booktrasaction_is_issued'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('document', models.FileField(upload_to='documents/')),
            ],
            options={
                'unique_together': {('book_title', 'book_author')},
            },
        ),
    ]
