# Generated by Django 4.1.7 on 2023-03-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_system', '0025_delete_bookdetails_delete_bookissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
