# Generated by Django 4.1.7 on 2023-04-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_system', '0027_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktrasaction',
            name='book_fine',
            field=models.IntegerField(default=0),
        ),
    ]
