# Generated by Django 4.1.7 on 2023-04-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_system', '0028_booktrasaction_book_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktrasaction',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
